export const ADD_TODO_OPTIMISTICALLY = "ADD_TODO_OPTIMISTICALLY";
export const POST_TODO_REQUEST = "POST_TODO_REQUEST";
export const POST_TODO_SUCCESS = "POST_TODO_SUCCESS";
export const POST_TODO_FAILURE = "POST_TODO_FAILURE";

export const PATCH_TODO_OPTIMISTICALLY = "PATCH_TODO_OPTIMISTICALLY";
export const PATCH_TODO_REQUEST = "PATCH_TODO_REQUEST";
export const PATCH_TODO_SUCCESS = "PATCH_TODO_SUCCESS";
export const PATCH_TODO_FAILURE = "PATCH_TODO_FAILURE";

export const DELETE_TODO_OPTIMISTICALLY = "DELETE_TODO_OPTIMISTICALLY";
export const DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_FAILURE = "DELETE_TODO_FAILURE";

export const TOGGLE_TODO = "TOGGLE_TODO";
export const UPDATE_TODO_TEXT = "UPDATE_TODO_TEXT";
export const UPDATE_TODO_PRIORITY = "UPDATE_TODO_PRIORITY";
export const UPDATE_TODO_DATE = "UPDATE_TODO_DATE";
export const REMOVE_TODO = "REMOVE_TODO";

export const SHOW_EDIT_MODAL = "SHOW_EDIT_MODAL";

export const RESET_TODO_ERROR = "RESET_TODO_ERROR";
