export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const HIDE_SESSION_EXPIRED_MESSAGE = "HIDE_SESSION_EXPIRED_MESSAGE";
